### ISSUE TITLE
Slope - Percent

### ISSUE THREAD

**Issue by keithlarson68** [USDA-NRCS/NRCS-Engineering-Tools---ArcGIS-Pro#13]
----------ERROR Start-------------------
 Traceback (most recent call last):
  File "C:\GIS\python_scripts\NRCS-Engineering-Tools---ArcGIS-Pro-master\SUPPORT\Calculate_Percent_Slope.py", line 358, in <module>
    arcpy.RefreshCatalog(watershedGDB_path)
AttributeError: module 'arcpy' has no attribute 'RefreshCatalog'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\GIS\python_scripts\NRCS-Engineering-Tools---ArcGIS-Pro-master\SUPPORT\Calculate_Percent_Slope.py", line 374, in <module>
    print_exception()     
  File "C:\GIS\python_scripts\NRCS-Engineering-Tools---ArcGIS-Pro-master\SUPPORT\Calculate_Percent_Slope.py", line 15, in print_exception
    AddMsgAndPrint("Traceback Info: \n" + tbinfo + "Error Info: \n    " +  str(sys.exc_type)+ ": " + str(sys.exc_value) + "",2)
AttributeError: module 'sys' has no attribute 'exc_type'
 Failed to execute (CalculatePercentSlope).

**Comment by dylan-harwell-usda** [comment]
Closing issue - `RefreshCatalog` is specific to arcpy for ArcMap (python 2.7). Tools are being redesigned and under development for Pro 3.3.
